### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.iot.device.common.transport_exceptions.ConnectionDroppedError
  fullName: azure.iot.device.common.transport_exceptions.ConnectionDroppedError
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - type: builtins.object
        type: builtins.BaseException
      type: builtins.Exception
    type: azure.iot.device.common.chainable_exception.ChainableException
  langs:
  - python
  module: azure.iot.device.common.transport_exceptions
  name: ConnectionDroppedError
  source:
    id: ConnectionDroppedError
    path: azure-iot-device\azure\iot\device\common\transport_exceptions.py
    remote:
      branch: master
      path: azure-iot-device\azure\iot\device\common\transport_exceptions.py
      repo: https://github.com/Azure/azure-iot-sdk-python
    startLine: 19
  summary: Previously established connection was dropped
  syntax:
    content: ConnectionDroppedError(message=None, cause=None)
  type: class
  uid: azure.iot.device.common.transport_exceptions.ConnectionDroppedError
references: []
