### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_07_01.models.error_response_py3.ErrorResponse
  - azure.mgmt.network.v2018_07_01.models.error_response_py3.ErrorResponseException
  fullName: azure.mgmt.network.v2018_07_01.models.error_response_py3
  langs:
  - python
  module: azure.mgmt.network.v2018_07_01.models.error_response_py3
  name: error_response_py3
  type: module
  uid: azure.mgmt.network.v2018_07_01.models.error_response_py3
references:
- fullName: azure.mgmt.network.v2018_07_01.models.error_response_py3.ErrorResponse
  isExternal: false
  name: ErrorResponse
  parent: azure.mgmt.network.v2018_07_01.models.error_response_py3
  uid: azure.mgmt.network.v2018_07_01.models.error_response_py3.ErrorResponse
- fullName: azure.mgmt.network.v2018_07_01.models.error_response_py3.ErrorResponseException
  isExternal: false
  name: ErrorResponseException
  parent: azure.mgmt.network.v2018_07_01.models.error_response_py3
  uid: azure.mgmt.network.v2018_07_01.models.error_response_py3.ErrorResponseException
